# 环境镜像
# micro-cloud镜像构建
version: "3"
services:
  micro-cloud-demo:
    image: micro/micro-cloud-demo:1.0-SNAPSHOT                  # 制定jenkins镜像
    container_name: micro-cloud-demo                            # 容器显示的名称
    restart: always                                             # 容器随docker启动而启动
    environment:
      - TZ=Asia/Shanghai
    ports:                                                      # 端口映射
      - 8002:8002
    volumes:                                                    # 映射数据卷
      - /mydata/micro-cloud-demo:/var/logs
  micro-cloud-system:
    image: micro/micro-cloud-system:1.0-SNAPSHOT
    container_name: micro-cloud-system
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mydata/micro-cloud-system/data:/var/logs
    ports:
      - 8001:8001
