# 环境镜像
version: "3"
services:
  jenkins:
    image: jenkins:latest                  # 制定jenkins镜像
    container_name: jenkins                # 容器显示的名称
    restart: always                        # 容器随docker启动而启动
    user: root
    environment:
      - TZ=Asia/Shanghai
    ports:                                 # 端口映射
      - 18080:8080
      - 50000:5000
    volumes:                               # 映射数据卷
      - /mydata/jenkins_home:/var/jenkins_home
  redis:
    image: redis:5.0
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - /mydata/redis/data:/data
    ports:
      - 6379:6379
  elasticsearch:
    image: elasticsearch:7.6.2              # elasticsearch镜像
    container_name: elasticsearch           # 容器名称
    restart: always
    environment:
      - "cluster.name=elasticsearch"        # 设置集群名称elasticsearch
      - "discovery.type=single-node"        # 以单一节点启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"    # 使用JVM内存大小
      - TZ=Asia/Shanghai
    volumes:
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins   #插件文件挂载
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data         #数据文件挂载
    ports:                                  # 端口映射
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    restart: always
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
      - TZ=Asia/Shanghai
    ports:
      - 5601:5601

  fluentd:
    image: fluent/fluentd:v1.10
    container_name: fluentd
    restart: always
    user: root                                   # root账号登录
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mydata/fluentd/log:/fluentd/log
      - /mydata/fluentd/fluent.conf:/fluentd/etc/fluent.conf
    depends_on:
      - elasticsearch                            # fluent在elasticsearch启动之后再启动
    links:
      - elasticsearch:es                         # es这个域名访问elasticsearch服务
    ports:
      - 24221:24221
      - 24222:24222
      - 24223:24223
      - 24224:24224



# micro-cloud镜像构建
#version: "3"
#services:
#  micro-cloud-demo:
#    image: micro/micro-cloud-demo:1.0-SNAPSHOT                  # 制定jenkins镜像
#    container_name: micro-cloud-demo                            # 容器显示的名称
#    restart: always                                             # 容器随docker启动而启动
#    environment:
#      - TZ=Asia/Shanghai
#    ports:                                                      # 端口映射
#      - 8002:8002
#    volumes:                                                    # 映射数据卷
#      - /mydata/micro-cloud-demo:/var/logs
#  micro-cloud-system:
#    image: micro/micro-cloud-system:1.0-SNAPSHOT
#    container_name: micro-cloud-system
#    restart: always
#    environment:
#      - TZ=Asia/Shanghai
#    volumes:
#      - /mydata/micro-cloud-system/data:/var/logs
#    ports:
#      - 8001:8001
